language: node_js
node_js:
  - 14
cache:
  npm: false
# before_script:
deploy:
  provider: pages
  local_dir: public
  # target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # committer-from-gh: true
  keep_history: true
  verbose: true
  on:
    branch: master
